import type { Locale } from '@/i18n/routing'

/**
 * Machine-translated content, generated by `npm run translate` (which calls
 * Google Cloud Translate with GOOGLE_TRANSLATE_API_KEY). The script rewrites
 * this file to import one JSON bundle per locale; until it runs, the map is
 * empty and every locale falls back to English exactly as before — so the repo
 * always builds whether or not translations have been generated yet.
 *
 * Values here are machine output. Hand-written overrides in i18n-content.ts are
 * layered ON TOP of these, so a reviewed human translation always wins.
 *
 * DO NOT edit by hand — re-run the generator instead.
 */

export type GeneratedBundle = {
  products?: Record<string, Record<string, unknown>>
  applications?: Record<string, Record<string, unknown>>
  catalog?: Record<string, Record<string, Record<string, unknown>>>
  /** UI chrome: source English string -> translation, consumed by t(). */
  ui?: Record<string, string>
}

export const generated: Partial<Record<Locale, GeneratedBundle>> = {}
