import HeroMark from '@/components/HeroMark'
import HeroTitle from '@/components/HeroTitle'

/**
 * The hero: a film, then the statement under it.
 *
 * ── Why the type is off the footage ─────────────────────────────────────────
 *
 * This has been built both ways. Strauss lays their type over the film, and
 * that version existed here and looked like theirs. Marc's call is the stack,
 * and the reasons hold up:
 *
 *  · The clip plays clean. Nothing sits on it, so it needs no scrim, and it
 *    shows at full strength instead of through a 45% brand wash plus a bottom
 *    gradient. On a 720p source that is the difference between a video you can
 *    see and one you can tell is there.
 *  · The type gets a flat ground, so it is legible whatever the frame is doing
 *    behind it — which matters on a 15-second loop nobody graded for text.
 *
 * The cost is height and the Strauss likeness. Both were accepted.
 *
 * ── The join is the whole problem ───────────────────────────────────────────
 *
 * A video band with a coloured box under it reads as two sections, which is
 * exactly the fault that got the first SectionBanner pulled off this page.
 * Three things stop it:
 *
 *  1. The section carries `bg-primary-3` and the copy block paints no ground of
 *     its own — it is the same surface, continuing.
 *  2. The foot of the film dissolves INTO that ground rather than ending on a
 *     cut. Getting that seam-free took three attempts; see the note on the
 *     gradient below, because the numbers in it are not arbitrary.
 *  3. The mark, the headline and the lede sit in one centred column on the same
 *     axis the film is composed on.
 *
 * ── The mark has no blend here ──────────────────────────────────────────────
 *
 * `mix-blend-mode: overlay` is the point of HeroMark — the footage reads
 * through the star so the mark belongs to the image. Over flat navy there is
 * nothing to read through and overlay just renders it muddy, so `blend={false}`.
 */
const Hero = ({ title, desc }: { title: string; desc: string }) => {
  return (
    /* `rounded-b-card` — Uri's 24px, bottom corners only. The band runs under
       the navbar to the top of the viewport, where there is nothing for a
       radius to be a radius against, which is exactly where Strauss puts
       theirs. The entry cards below sit on the page's own white ground, so this
       corner is what ends the hero. */
    <section data-note="hero" className="bg-primary-3 rounded-b-card relative isolate w-full overflow-hidden">
      {/* ── THE FILM ──────────────────────────────────────────────────────────
          Sized in svh rather than by aspect ratio: the source is 16:9, and
          full-bleed on a wide desktop a 16:9 box is over 800px tall on its own
          — the whole hero before a word is read. A viewport fraction crops it
          instead, which is what `object-cover` is for.

          `object-[50%_45%]` biases the crop up. The subject is the technician's
          hands at the bench, and a centred crop cuts them at the frame's waist. */}
      <div className="relative h-[46svh] w-full lg:h-[50svh]">
        {/* Streaming from EID's own ImageKit account rather than committed, so
            the clip can be recut and swapped without a deploy, and ImageKit
            answers range requests so the browser streams instead of blocking on
            the whole 1.3MB.

            `poster` is the frame at t=3s, generated by ImageKit from the same
            file (`/ik-thumbnail.jpg?tr=so-3`). First paint is a real frame of
            the real video, and there is no second asset to keep in sync — recut
            the clip and the poster follows.

            muted + playsInline  — autoplay is refused without both, and on iOS
                                   playsInline stops it going fullscreen.
            autoPlay + loop      — background film, no controls, no end state.
            preload="metadata"   — the poster covers first paint, so there is no
                                   reason to spend the connection on the whole
                                   file before the page below has rendered. */}
        <video
          className="size-full object-cover object-[50%_45%] motion-reduce:hidden"
          src="https://ik.imagekit.io/qcvroy8xpd/EID%20VIDEO%20HERO.mp4"
          poster="https://ik.imagekit.io/qcvroy8xpd/EID%20VIDEO%20HERO.mp4/ik-thumbnail.jpg?tr=so-3"
          autoPlay
          loop
          muted
          playsInline
          preload="metadata"
          aria-hidden
        />

        {/* Reduced motion gets the poster and nothing else. A background film is
            exactly the kind of unrequested movement that setting exists for, and
            `motion-reduce:` on the pair swaps them with no JavaScript and no
            layout shift — same box, same crop. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          className="absolute inset-0 hidden size-full object-cover object-[50%_45%] motion-reduce:block"
          src="https://ik.imagekit.io/qcvroy8xpd/EID%20VIDEO%20HERO.mp4/ik-thumbnail.jpg?tr=so-3"
          alt=""
          aria-hidden
        />

        {/* A ground for the navbar, which is transparent over this hero and has
            white links.

            ⚠ THE TWO GRADIENTS ON THIS BAND HAVE TO BE BUDGETED TOGETHER, and
            that is what went wrong: this one was 192px and the join below was
            176px, against a band of about 373px at lg. 368 of 373 — the pair
            covered essentially the whole film, which is why it looked washed
            rather than lit.

            Both are now roughly a third shorter and the band a little taller,
            which leaves ~165px of the frame at full strength in the middle.
            Before changing either number, add them and compare against the
            band height.

            Shorter but slightly stronger at the very top (70% against 62%), so
            the navbar keeps its contrast out of a shorter ramp. Brand navy
            rather than near-black: against cool blue-grey footage black is a
            foreign colour and reads as a bar laid on top. */}
        <div aria-hidden className="from-primary-3/70 via-primary-3/14 absolute inset-x-0 top-0 h-28 bg-linear-to-b via-50% to-transparent lg:h-32" />

        {/* THE JOIN, and the numbers here are load-bearing.

            A two-stop ramp only reaches full opacity on its very last pixel row,
            so the stretch above it stays slightly translucent and the bright
            bench edge in the footage shows through as a pale streak — precisely
            the seam the fade exists to prevent. A mid stop alone was not enough
            either; 99% opaque over a bright edge is still not 100%.

            So: 92% at 60% down, then fully solid at `to-86%` rather than at the
            boundary. The last seventh is flat navy with no video under it, and
            there is nothing left to show through. Those two percentages held
            when the ramp was shortened from 176px to 112px — they are
            proportional, so the seam stayed fixed.

            `from-primary-3/0` rather than `from-transparent`: same rendered
            result, since CSS interpolates gradient alpha premultiplied, but it
            states the intent — this fades the section's own ground in, it does
            not fade some unrelated colour out. */}
        <div aria-hidden className="from-primary-3/0 via-primary-3/92 to-primary-3 absolute inset-x-0 bottom-0 h-24 bg-linear-to-b via-60% to-86% lg:h-28" />
      </div>

      {/* ── THE STATEMENT ─────────────────────────────────────────────────────
          The lockup is still Strauss's, even though its position is not: mark,
          then headline at `mt-1.5`, which is their `row-gap: 5px` and the
          measurement the composition turns on — their monogram is not above the
          headline, it is part of it.

          The type scale is the site's own. `clamp(1.9rem, 4.4vw, 3.5rem)` is
          what PageHero's `full` variant renders, so the home h1 matches About,
          Quality and the product pages rather than a competitor's fixed steps.
          Leading comes from HeroTitle.

          No CTAs — the header's Contact button is directly above on every page,
          and the two entry cards below carry Products and Applications. */}
      <div className="relative z-10 pt-10 pb-14 lg:pt-12 lg:pb-20">
        <div className="container flex flex-col items-center text-center">
          <HeroMark blend={false} />

          <HeroTitle title={title} className="mt-1.5 text-[clamp(1.9rem,4.4vw,3.5rem)]" />

          {/* `text-pretty` because the line runs to two at this measure and was
              ending on a single word; pretty is the one wrap mode that exists to
              pull a word back off an orphaned last line.

              mt-6 rather than the lockup's 6px, and that gap is doing work: it
              tells the eye the mark and the headline are one object and this
              sentence is a second one.

              64ch, not 52: at the narrower measure the line broke three ways and
              left "end users." alone on the last one, which is the one phrase in
              the hero that should not read as an afterthought. */}
          <p className="mt-6 max-w-[64ch] text-[0.95rem] leading-relaxed text-pretty text-white/80 md:text-base">{desc}</p>
        </div>
      </div>
    </section>
  )
}

export default Hero
