import HeroMark from '@/components/HeroMark'
import HeroTitle from '@/components/HeroTitle'
import ScrollCue from '@/components/ScrollCue'

/**
 * The hero: type on the film.
 *
 * ── What changed, and what it bought ────────────────────────────────────────
 *
 * This was a stack — film on top, statement underneath on flat navy, joined by
 * a gradient. That arrangement spent a lot of the frame on treatment rather
 * than on picture:
 *
 *   navbar scrim      112-128px
 *   join gradient      96-112px
 *   the navy block    ~300px of solid colour under the film
 *
 * Marc's call is to drop all of it and put the words on the video. The join
 * gradient goes entirely — with no navy block beneath, it has nothing to join
 * to — and the section is one full-bleed film again.
 *
 * ── The one treatment that stays, and why ───────────────────────────────────
 *
 * A single bottom-up scrim behind the copy. Not the old 45% brand wash over
 * the whole frame: this is transparent across the top two thirds so the film
 * plays clean, and only firms up under the words.
 *
 * It is not optional. The home clip is a laboratory scene with white coats and
 * bright benches, and white type dropped straight onto that is unreadable at
 * several points in a 15-second loop. The test is not whether it reads on the
 * poster frame — it is whether it reads on every frame. The scrim is the
 * cheapest thing that guarantees that, and at these stops it costs the picture
 * very little.
 *
 * `primary-3` rather than black: against cool blue-grey footage a black scrim
 * is a foreign colour and reads as a bar laid on top rather than as shading.
 *
 * ── Height is a floor ───────────────────────────────────────────────────────
 *
 * `min-h`, not `h`. A longer headline takes the room it needs rather than
 * clipping, and the next section still shows above the fold at these values —
 * which is the mechanism behind the whole rhythm brief.
 */
const VideoHero = ({
  title,
  desc,
  video,
  poster,
  /** Minimum height for the band. About runs shorter than home. */
  minHeight = 'min-h-[60svh]',
  /** Crop bias. Defaults to slightly above centre. */
  objectPosition = 'object-[50%_45%]',
  scrollCue = false,
}: {
  title: string
  /** Optional. About runs without one — the headline carries the page. */
  desc?: string
  video: string
  poster: string
  minHeight?: string
  objectPosition?: string
  scrollCue?: boolean
}) => {
  return (
    /* `rounded-b-card` — Uri's 24px, bottom corners only. The band runs under
       the navbar to the top of the viewport, where there is nothing for a
       radius to be a radius against. */
    <section
      data-note="hero"
      className={`bg-primary-3 rounded-b-card relative isolate flex w-full items-end overflow-hidden ${minHeight}`}
    >
      {/* Streaming from EID's own ImageKit account rather than committed, so a
          clip can be recut and swapped without a deploy, and ImageKit answers
          range requests so the browser streams instead of blocking on the
          whole file.

          `poster` is a frame generated by ImageKit from the same file
          (`/ik-thumbnail.jpg?tr=so-N`). First paint is a real frame of the
          real video and there is no second asset to keep in sync.

          muted + playsInline  — autoplay is refused without both, and on iOS
                                 playsInline stops it going fullscreen.
          loop                 — background film, no controls, no end state.
          preload="metadata"   — the poster covers first paint.

          NO `autoPlay`, and that is the point. With it the clip starts as soon
          as the browser can play it, which is behind the full-screen loading
          panel — several seconds of a short loop spent where nobody can see
          it, so the first thing a visitor actually sees is the middle of a
          shot. `data-hero-video` hands the start over to SiteIntro, which rewinds
          and plays it once the swoosh has finished. See releaseHeroVideo,
          including why a refused play() is swallowed rather than treated as
          an error. */}
      <video
        className={`absolute inset-0 -z-20 size-full object-cover ${objectPosition} motion-reduce:hidden`}
        src={video}
        poster={poster}
        data-hero-video
        loop
        muted
        playsInline
        preload="metadata"
        aria-hidden
      />

      {/* Reduced motion gets the poster and nothing else — same box, same
          crop, no JavaScript and no layout shift. */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        className={`absolute inset-0 -z-20 hidden size-full object-cover ${objectPosition} motion-reduce:block`}
        src={poster}
        alt=""
        aria-hidden
      />

      {/* Legibility, and only that. Clear from the top through 45%, so the
          upper frame is untouched picture; firms up under the copy. */}
      <div
        aria-hidden
        className="from-primary-3/88 via-primary-3/30 absolute inset-0 -z-10 bg-linear-to-t via-45% to-transparent"
      />

      {/* A ground for the navbar, which is transparent over this hero and has
          white links. Short and light — enough for the links, not enough to
          read as a bar across the top of the film. */}
      <div
        aria-hidden
        className="from-primary-3/55 absolute inset-x-0 top-0 -z-10 h-24 bg-linear-to-b via-transparent to-transparent lg:h-28"
      />

      {/* THE LOCKUP. Mark, then headline at `mt-1.5` — Strauss's `row-gap:
          5px`, and the measurement the composition turns on: their monogram is
          not above the headline, it is part of it.

          `blend={false}`, and this is the second time that call has been
          re-made. `mix-blend-mode: overlay` is the point of HeroMark and it
          works beautifully over consistently dark footage — but the mark sits
          high in the frame, above where the legibility scrim starts, so on the
          home clip it lands on a white lab coat. Overlay against a bright
          ground turns the white star into a blue smudge, and it does it on
          some frames of the loop and not others, which is worse than a
          consistent result either way.

          A background film cannot be relied on to be dark where a blended
          element needs it to be. Solid white is correct on both clips. */}
      <div className="relative z-10 w-full pt-32 pb-14 lg:pt-36 lg:pb-16">
        <div className="container flex flex-col items-center text-center">
          <HeroMark blend={false} />

          <HeroTitle title={title} className="mt-1.5 text-[clamp(1.9rem,4.4vw,3.5rem)]" />

          {desc && (
            <p className="mt-6 max-w-[64ch] text-[0.95rem] leading-relaxed text-pretty text-white/85 md:text-base">
              {desc}
            </p>
          )}

          {scrollCue && <ScrollCue className="mt-9" />}
        </div>
      </div>
    </section>
  )
}

export default VideoHero
